### ISSUE TITLE
Is there a way to generate PlantUML from Emacs Lisp? Thank you very much.

### ISSUE THREAD

**Issue by suliveevil** [ginqi7/plantuml-emacs#2]
I want learn Emacs Lisp from someone's plugin by understand their logic using PlantUML.

**Comment by ginqi7** [comment]
I also haven't seen a tool that can convert emacs lisp to UML.
But I found a package that can convert emacs lisp to graphviz, and maybe it can help you.

https://github.com/mtekman/elisp-depmap.el

**Comment by suliveevil** [comment]
Thank you very much.
